### ISSUE TITLE
Repo Rebuild

### ISSUE THREAD

**Issue by Awetspoon** [santacrab2/PKHeX-Plugins#13]
Im unsure if this is something to even report but wanted to know if it means anything. i have copied the repo and then done a rebuild on the release. its builds fine but i get this message in visual studio wanted to pcik your brains if possible please. 
![image](https://github.com/santacrab2/PKHeX-Plugins/assets/122938825/4a779c7a-b9da-4d10-88d8-11e60e09dbee)

**Comment by santacrab2** [comment]
They are just warnings of potential issues that are not best practice, however they are all handled within the code so as far as I'm aware its fine.
