### ISSUE TITLE
Living dex generation priority

### ISSUE THREAD

**Issue by k20stitch** [santacrab2/PKHeX-Plugins#14]
**Describe the bug**
I'm not sure if this is actually a bug or not, but does prioritize game version affect living dex generation? I'm setting it to US for example and my game is UM, Lugia is always generated from the Space Wilds Encounter but Ho-Oh always ends up being an event. Native only set to true or false has no affect

**To Reproduce**
Set prioritize gameversion to true
Set to US
Generate living dex in UM
Ho-Oh is always an event

**Expected behavior**
Am hoping to get the US/UM encounter for each, is there another feature or setting I can toggle?

**Comment by santacrab2** [comment]
I can not replicate with the current listed steps. I even tried several different settings and set ups to try to recreate the issue and I just couldn't both Lugia and Ho-Oh came from Ultra Space. However there does seem to be an issue related to the trainer database folder that I am currently investigating, just to update you.

**Comment by k20stitch** [comment]
I am using the trainer info stuff. I’ll try a clean folder with clean settings and try again to see what might be causing this. Thanks for taking a look.

can you at least confirm that prioritize game version and prioritize encounter should affect living Dex generation?

**Comment by santacrab2** [comment]
It does because that is a PKHeX setting that it is applying to the PKHeX EncounterMoveSetGenerator class for when it searches encounters for any legalization process. However, living dex uses very basic showdown sets to legalize, so it is going to favor first legal encounter.

**Comment by k20stitch** [comment]
So I just downloaded a clean version of pkhex (official release), It's in a new folder with no settings or other folders. I create a plugins folder and drop the automod dll in with a build from your cherry tree on 1/31/2024.

I open PKHeX, set the game version to Ultra Moon. Generate a living dex and these are the results.
![image](https://github.com/santacrab2/PKHeX-Plugins/assets/25312232/6ad3035e-40e7-411e-97e4-b74dcfde2d0a)
![image](https://github.com/santacrab2/PKHeX-Plugins/assets/25312232/966693c3-fb1a-454d-8944-76f42bc713a7)

No settings, no changes to anything, no trainer info supplied. Let me know if you need a copy of anything.

Edit: This appears to happen with other Pokemon that are exclusive to Ultra Sun like "Raikou", it favors the event instead of the Wild Encounter from the game's counterpart.

**Comment by santacrab2** [comment]
I see now. I have no idea why I thought the event was shiny....anyways.... 

This is working as intended.

if you don't prioritize game -> Ultra Moon is going to be first, which means the first legal encounter for Ultra moon for Ho-Oh will be the event, this would be the same for Ultra Sun and Lugia.

If you Prioritize the game then its going to favor that game for all encounters. So if you Prioritize Ultra Sun on an Ultra Moon save then Lugia will be the event and Ho-Oh will be from Wilds. 

It's not going to skip over the event when its perfectly legal encounter for the prioritized/initial version.


It sounds like you are wanting specific encounters for specific pokemon which is not what the Living Dex Generation is meant for. It is meant for quick legal mass creation. I recommend using the mass showdown import feature to build Pokemon the way you want!

**Comment by santacrab2** [comment]
The trainer folder bug was related to me having the Check Active Handler legality check turned on, so not really a bug just really strict legality checks just for anyone reading this in the future/fyi for poster.
