### ISSUE TITLE
Fusion forms

### ISSUE THREAD

**Issue by ghost** [santacrab2/PKHeX-Plugins#15]
i've noticed that when a "living dex" is generated with all forms, it lack every fusion form (calyrex with glastrier etc , necrozma etc) is it possible to implement all fusions forms while generating living dex?

**Comment by santacrab2** [comment]
No it is not. 
1. You can only have 1 fusion form for each set, so for example you can only have Calyrex Ice rider or Shadow Rider in your save file not both at the same time
2. The originals are still stored within the save file for de-fusion, so that would also need to be handled.

**Comment by ghost** [comment]
i did it manually the same way as adding male and female pokemon that have differrent look (like Meowstic, Indeedee etc) i have a save with calyrex fusions and calyrex separate from glastrier etc, same with necrozma, kyurem) that's why i asked, it as pkhex don't see my save as illegal

**Comment by santacrab2** [comment]
Try to unfuse all of the fusions you have in there and let me know how it goes.

Then after you do that I want you to explain how you would get both a shadow rider and an ice rider without using PKHeX at all and I want a screenshot of having both, again without using PKHeX at all. 

When you can't do that because its not actually possible to do without hacks you will know why I am not implementing it.

![image](https://github.com/santacrab2/PKHeX-Plugins/assets/79347566/7560daef-d22b-46ed-92c3-db27b382dd02)

**Comment by ghost** [comment]
ok i understand why you don't do the fusion , basically i wanted to keep them separately and in their fusions forms so no need to unfused them 
maybe some male female form can be added anyway like i've seen Meowstic, Indeedee 
basicaly i "captured legaly" all i can capture and only "generate" all i can't get with an hacked console (with no online), the "living dex" allow me to see all pokemons that can be in the game with all forms that can be inside, it's mostly a reference for me to fill pokemon box
thanks anyway for the incredible tools

**Comment by santacrab2** [comment]
I can fix Meowstic and Indeedee it should produce both forms for those species particularly as their genders are their forms this is not the case with the majority of the species. I actually thought it was already handling those but it seems not so I will adjust that.

For references on what's in the game, I do recommend using https://www.serebii.net/scarletviolet/paldeapokedex.shtml 

it has pages for what's in the pokedex, what's available in the game and not in pokedex and what's transfer only.

**Comment by ghost** [comment]
cool thanks :)

**Comment by santacrab2** [comment]
Indeedee forms and Meowstic forms are now produced in living dex generation with latest commit! 

Thank you for catching that!
