### ISSUE TITLE
Error with visual studio when I rebuild the project

### ISSUE THREAD

**Issue by NEKpewar** [santacrab2/PKHeX-Plugins#16]
I have many problems when I rebuild the plugins project 

I did the Bleeding Edge Builds method to update pkhex and ALM (your branch), I put the pkhexcore.dll into the pkhexcore's nuget folder but when I rebuild I have the errors (image), before I never had a problem when I rebuild but now I have these problems 

![image](https://github.com/santacrab2/PKHeX-Plugins/assets/21049981/83fb388a-47de-4bf3-a78c-a4f3b6b24889)

**Comment by santacrab2** [comment]
The branch that has the fixes for the latest pkhex commits has not been merged as there are still bugs in pkhex that need to be addressed.

**Comment by santacrab2** [comment]
I merged, it should work as expected now. Fair warning there are some sets that are still failing to legalize, these will be addressed in future  commits
