### ISSUE TITLE
possible to legalize the missing HOME tracker?     

### ISSUE THREAD

**Issue by ELY3M** [santacrab2/PKHeX-Plugins#19]
**Describe the bug**
After I updated both Pkhex and this plugin.     
any Pokemon that you generated from encounter database or anywhere.   
used to be "legal" in older version of pkhex.    
will have warning for missing home tracker.  this is normal.      
it is not a bug in pkhex.   

but I wonder if it is possible to legalize this problem of missing home tracker?      

as I was playing around, I put in random tracker number and it became legal!  but 
I will NOT be expecting that Pokemon to be able to transfer to HOME at all!!!!!       
I think HOME trackers are server-side and they will verify.       

**To Reproduce**
load up your save from scarlet or violet.  
check the Pokemon and some of them would have warning about missing tracker. 
Or  use the encounter database and search for one of Pokemon like Keldo or any Pokemon that is not from Scarlet or Violet.   

**Expected behavior**
It will show that it is illegal and warn you that it wont be able to be transferred to HOME.     
I know this is normal and it should happen if it do not have HOME tracker.    

**Screenshots**

**Additional context**

**Comment by ELY3M** [comment]
Nevermind,  it is not possible for us to validate Home Tracker Numbers right now..... 

more info here:  
https://projectpokemon.org/home/forums/topic/56296-read-home-tracker-value/

**Comment by ELY3M** [comment]
actually, it is good that Pkhex added this function to check if the Pokemon needs home trackers or not and Let us know if they cant be transferred to home or not.

**Comment by santacrab2** [comment]
This has been a feature for quite sometime. The Default setting just recently changed from "Fishy" to "Invalid".

It will never be possible to spoof a tracker without directly hacking Nintendo's servers which is illegal, so it will never be possible.
