### ISSUE TITLE
Legendary issues

### ISSUE THREAD

**Issue by chimel23** [santacrab2/PKHeX-Plugins#20]
Why do non ScaVi legendaries usually not generate a correct met location with auto legality?

**Comment by santacrab2** [comment]
Ensure that you have checked your PKHeX legality settings as Pokemon that require Home Trackers are now flagged as Illegal by PKHeX by default and so Auto-Mod will not be able to find a matching encounter.

You may also need to set the Plugin setting to AllowHomeTransferGeneration to True.

**Comment by ELY3M** [comment]
@chimel23 
I have same issue  Please read  https://github.com/santacrab2/PKHeX-Plugins/issues/19
