### ISSUE TITLE
Livehex bug in 24.06.03 here is the error that PKHeX spits out for me.

### ISSUE THREAD

**Issue by Aura67** [santacrab2/PKHeX-Plugins#26]
have the latest PKHeX with your plugins get this error in livehex
![336552299-03fcc132-8e68-4b73-bad9-84ad2ae67d9d](https://github.com/santacrab2/PKHeX-Plugins/assets/152577275/bf81059a-b9ff-4607-9acc-49631141a019)
and when I want to create a Living Dex windows is stuck.

**Comment by santacrab2** [comment]
I can not replicate based on the provided information.

**Comment by hexbyt3** [comment]
> have the latest PKHeX with your plugins get this error in livehex ![336552299-03fcc132-8e68-4b73-bad9-84ad2ae67d9d](https://private-user-images.githubusercontent.com/152577275/336555480-bf81059a-b9ff-4607-9acc-49631141a019.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjQ0NjksIm5iZiI6MTcxNzUyNDE2OSwicGF0aCI6Ii8xNTI1NzcyNzUvMzM2NTU1NDgwLWJmODEwNTlhLWI5ZmYtNDYwNy05YWNjLTQ5NjMxMTQxYTAxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxODAyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmZlMzNiNThlZjE0MDI3YmU0MTU4ZTdhMzgwNTNlZWIxZGM3MWY3NzdjNjk3MWZlZDkwYTY0NzBjYTRkNmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dJCYq1KUmqmzgchsby3CoJUiaZerhLN6K8L_0Oe_bNY) and when I want to create a Living Dex windows is stuck.

Make sure everything is updated if you built yourself.  That error is due to a Plugin not being up to date.  I got it earlier and it was due to TeraFinder not being updated.  

But since I updated everything, it works like it should.

![image](https://github.com/santacrab2/PKHeX-Plugins/assets/80122551/343643ec-7694-4e22-b9e0-690e6e70f6bd)
