### ISSUE TITLE
Hidden Ability and Others Abilities

### ISSUE THREAD

**Issue by Niklasano** [santacrab2/PKHeX-Plugins#29]
Hi,

Since the last update, the Auto-Legality Mod doesn't select properly the hieden ability of any pokemon when to try to legalize or import one

Exemple:
Here the prompt :
<img width="567" alt="prompt" src="https://github.com/user-attachments/assets/f11625e8-0108-4b7f-857a-657d51bf9153">

Here the result (everytime):
![image](https://github.com/user-attachments/assets/5e8cfe9c-9d6c-446d-a235-8e72acc63d88)

when hidden ability is prompted, the second ability is always set up et not the hidden

I don't know if it is a bug or a configuration of my pkhex

**Comment by Niklasano** [comment]
I add this too, if i want to generate a pokemon with the second ability, it will be always the first ability who will be generated

**Comment by Niklasano** [comment]
This is a 3ds Ultra Moon save, on legend arceus, violet or sword, it is works properly

**Comment by santacrab2** [comment]
This has already been addressed with this commit https://github.com/santacrab2/PKHeX-Plugins/commit/7be007c7814a18dfd4bbc62ca17caf159d83870a . Please use the development build until the next release. You can install this through either the setup_bleedingedge.exe powershell script or download from the azure pipeline connected to this repo. https://dev.azure.com/santacrab2/PKHeX-Plugins/_build/results?buildId=158&view=artifacts&pathAsName=false&type=publishedArtifacts
