### ISSUE TITLE
Can't download or install

### ISSUE THREAD

**Issue by Mark1817** [santacrab2/PKHeX-Plugins#30]
_**Detected at: 21/09/2024 10:25:26

Web address: https://objects.githubusercontent.com/github-production-release-asset-2e65be/528385436/e61188f9-2414-4388-98d1-4cd8b188cc88?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240921%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240921T092526Z&X-Amz-Expires=300&X-Amz-Signature=45867d8824ed457b407c257c1c22773f007d21dd834f9579f141005cbf4b3dbf&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dsetup_stable.exe&response-content-type=application%2Foctet-stream

Reason: object is infected [VHO:Backdoor.Win32.Convagent.gen](http://redirect.kaspersky.com/?hl=en-GB&target=securelist&rpe=1&function=search&VN=VHO:Backdoor.Win32.Convagent.gen)**_

i paused the protection and managed to download it but the the netframe work then had an issue, and im sure once the protection starts up again it will tell me there is a problem and i need to disinfect.

**Comment by santacrab2** [comment]
This seems like a Windows Defender false positive. Beyond that I am not sure what could possibly be triggering this. Try downloading the dll directly and installing instead of using the setup exe's. You will likely need to unblock the dll but this should avoid the windows defender error.
