### ISSUE TITLE
Unown forms don't appear

### ISSUE THREAD

**Issue by KprojectsKurt** [santacrab2/PKHeX-Plugins#31]
When using the "Generate Living Dex" on Emerald (and also tried on Scarlet, but it's buggier there) with "All forms" set on "True", Unown-A appears, but the rest of the forms do not.
Emerald:
![image](https://github.com/user-attachments/assets/3a7a471e-4757-4266-b2a5-56c109ae97c2)
Scarlet (Unown and Wobuffet don't appear):
![image](https://github.com/user-attachments/assets/d3e6c5c2-77ef-4cd3-8130-0a41d67780c1)

**Comment by santacrab2** [comment]
I will investigate emerald unown.

Unown and wobbuffet are not in SV, so that is functioning correctly.

**Comment by KprojectsKurt** [comment]
Oh my bad on the Scarlet part hehe i was unaware

**Comment by santacrab2** [comment]
solved on latest commit, thank you for the bug report!
