### ISSUE TITLE
Sword/Shield boxes not working

### ISSUE THREAD

**Issue by Myaestro** [santacrab2/PKHeX-Plugins#36]
If I run livehex in word/shield, I can't see anything in the box and edit it. It happens with or without the internet. Could you possibly fix this? Thank you always for your hard work!

**Comment by santacrab2** [comment]
I can not replicate. A common issue with Sword/Shield is the local communication mode that the game forces. Ensure you are either running ldn_mitm or you are connected to the internet in game prior to connecting livehex.
